### PR TITLE
review test links #357

### PR DESCRIPTION
**Pull request by arve0**
- add link tester to travis CI
- add link tester to `yarn run testall`
- fix code from comments in PR #357

TODO: Fix links. I need help with this, maybe fix in `src/route*.js`?

### CODE REVIEW

**Comment by NorwegianKiwi** [comment]
Suggestion (although not sure if this is the optimal solution): Make a script in webpack config to traverse the links in oppgave-repo, and copy those files using f.ex. https://github.com/kevlened/copy-webpack-plugin.

**Comment by teodorlu** [comment]
### Summarizing the results from the links I checked

- I've been conflating old/new/local site
- When I edit tasks _locally_, I use `./gulp`, which behaves differently from the live site regarding `.html`-extensions

### 404 links seem to add more /beta/ infixes

This may not be new information?

To reproduce:

1. Try to go to `http://oppgaver.kidsakoder.no/beta/scratch/veiledninger/kom_i_gang_med_scratch.html`
2. Get redirected to `http://oppgaver.kidsakoder.no/beta/beta/scratch/veiledninger/kom_i_gang_med_scratch.html`
3. Get redirected to

### Responses to comments from @arve0 

Overall: I've been conflating the live beta site, the live old site and the locally running file. Per now, I guess the beta (new) site most important. For later, it would be neat if running `.gulp` behaved similarly.

> Agree. Link test should not give false positives. I've several of the links in  https://skagevang.github.io/beta, none are not false positives. @teodorlu Are you mixing up oppgaver.kidsakoder.no (codeclub_lesson_builder), with the new site (codeclub-viewer currently at https://skagevang.github.io/beta/)?

Yup, my bad.

> I'm not following you. The link tester is not running ./gulp. Do you mean yarn run build?

Ref old/new/local conflation.

Seems like you have this under control.

**Comment by arve0** [comment]
> For later, it would be neat if running .gulp behaved similarly.

@teodorlu You may run `./gulp links` today (and yesterday) 😄 This PR is a direct copy of [existing link checker in codeclub_lesson_builder](https://github.com/arve0/codeclub_lesson_builder/blob/master/check-links.js). Existing link checker is what runs in travis CI when doing a PR to [kodeklubben/oppgaver](https://github.com/kodeklubben/oppgaver). [For example this test of your PR](https://travis-ci.org/kodeklubben/oppgaver/builds/258848122?utm_source=github_status&utm_medium=notification).

**Comment by arve0** [comment]
>  Make a script in webpack config to traverse the links in oppgave-repo, and copy those files using f.ex. https://github.com/kevlened/copy-webpack-plugin.

That may solve missing resource files.

What about `scratch/index.html` -> `scratch` (missing `/` in end)? How do we solve that?

**Comment by NorwegianKiwi** [comment]
Perhaps this will work better after merging in https://github.com/kodeklubben/codeclub-viewer/pull/388?

This PR might also need to have https://github.com/kodeklubben/codeclub-viewer/issues/386 solved as well, but that should be relatively easy.

**Comment by arve0** [comment]
> Perhaps this will work better after merging in #388?

Unsure what "this" refers to.

In case "this" refers to this PR: The PR works as advertised; Failing test in CI when links are not reachable.

In case "this" refers to "checking links": Maybe. One would know if this PR was merged to master. Then every preceding PR that should fix the problem would start showing approved tests from CI.

In my opinion, having a failing master is correct in this case. Not doing so is seeping under the rug.

**Comment by NorwegianKiwi** [comment]
@arve0 has said he is not doing more on this PR. Closing this PR for now. To be continued with #151. If necessary, reuse code from this PR.

**Pull request closed without merging**
